
export default{
  MOVIES_RECEIVED: 'MOVIES_RECEIVED',
  MOVIE_CREATED: 'MOVIE_CREATED',
  SELECT_MOVIE: 'SELECT_MOVIE',
  NOTE_CREATED: 'NOTE_CREATED',
  NOTES_RECEIVED: 'NOTE_RECEIVED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  APPLICATION_STATE: 'APPLICATION_STATE'
}
